### ISSUE TITLE
Editing the Readme File

### ISSUE THREAD

**Issue by aurorachilles** [vaibhav-zemo/Leetcode-Solutions#10]
I would like to contribute by editing the Readme file. Is there anything specific you want me to include in the readme file? Thank you.

**Comment by vaibhav-zemo** [comment]
Okay you can do this. I don't need any specification thankyou.

**Comment by vaibhav-zemo** [comment]
@aurorachilles is now handling this issue

**Comment by aurorachilles** [comment]
I am having a permission denied to repo. URL returning error 403. Am I given permission to write this repo?

**Comment by vaibhav-zemo** [comment]
Do clone then make pr. I think you are directly making changes, Is this something?

**Comment by aurorachilles** [comment]
I did clone it. I had the same problem on another repo which was fixed after I was invited as a collaborator.

**Comment by aurorachilles** [comment]
Oh, I got it. Thanks.
